# DockerImage： Simple API
# =======================================================
version: '2'
services:
  web:
    image: kawoukaka/simple_api:latest
    container_name: simple_api
    ports:
      - "8001:8001"
    environment:
      - "SERVER_TIER=dev"
    user: www-data
    logging:
      driver: "json-file"
