# DockerImage： Simple API
# =======================================================
version： ’2‘
services:
  web:
    image: kawoukaka/simpleAPI:latest
    ports:
      - "8001:8001"
    environment:
      - "SERVER_TIER=dev"
    user: www-data
    logging:
      driver: "json-file"
